version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mariadb
    networks:
      - helmy-network
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: helmy_auth
      MYSQL_USER: helmy_user
      MYSQL_PASSWORD: helmy_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - helmy-network
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  helmy-network:
    driver: bridge
